[package]
name = "my-keepass"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dotenv = "0.15"
rand = "0.8"
aes-gcm = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes = "0.8"
base64 = "0.21"
